name: hegelmann_order_automation
description: "Hegelmann order automation."

publish_to: 'none'

version: 1.1.3

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # StateManager/ui/ux
  flutter_screenutil: ^5.9.3
  responsive_framework: ^1.5.1
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0

  # injection
  get: ^4.6.6

  # Animation/Icon/Notification
  flutter_svg: ^2.0.16
  flutter_animate: ^4.5.2
  lottie: ^3.1.3
  top_snackbar_flutter: ^3.1.0
#  quickalert: ^1.1.0

  # Nav
  go_router: ^14.6.1

  # Utils
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  intl: any
  gap: ^3.0.1
  date_format: ^2.0.9
  geolocator: ^13.0.2
  email_validator: any
  easy_date_timeline: ^2.0.4
  shimmer: ^3.0.0
  timeago: ^3.7.0
  money_formatter: ^0.0.6
  fl_chart: ^0.69.2
  timezone: ^0.10.0
  device_preview_plus: ^2.2.4
  isolate_manager: ^5.7.3
  flutter_expandable_table: ^2.1.0
#  omni_datetime_picker: ^2.0.6
#  board_datetime_picker: ^2.4.0
#  file_picker: ^8.1.4

  #security
  public_ip_address: ^1.2.1

  #logger
  talker_flutter: ^4.5.1
  talker_bloc_logger: ^4.5.1
  connectivity_plus: ^5.0.2

  # Firebase database
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_ui_firestore: ^1.7.0
  cloud_functions: ^5.1.5
#  firebase_auth: ^5.4.1
  firebase_pagination: ^4.1.0

  # localization
  flutter_localization: ^0.2.2

  # Theme
  flex_color_scheme: ^8.0.1

  #Map
  osrm: ^0.0.8
  flutter_map: ^8.0.0
  latlong2: ^0.9.0
  flutter_map_cancellable_tile_provider: ^3.1.0

  #version
  package_info_plus: ^8.2.1

  cupertino_icons: ^1.0.8

  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf


    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/postalcodes/
